#!/bin/sh

#PBS -M tehsheng@umich.edu
#PBS -m abe

#PBS -l nodes=1:ppn=8,mem=32000mb,walltime=10:00:00
#PBS -j oe
#PBS -V

#PBS -A mdatascienceteam_flux
#PBS -l qos=preempt
#PBS -q flux


#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi

module load anaconda3
module load gcc/4.8.5

python Model_accident_person_001.py



